#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.arm.elf.A8Fnv{1,0,5.2,4
#
app.xea8fnv: package/cfg/app.xea8fnv.mak

clean::
	-$(RM) package/cfg/app.xea8fnv.mak
