#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = configPkg
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
C:/ti/xdctools_3_30_06_67_core/packages/xdc/utils.js:
package.mak: C:/ti/xdctools_3_30_06_67_core/packages/xdc/utils.js
C:/ti/xdctools_3_30_06_67_core/packages/xdc/xdc.tci:
package.mak: C:/ti/xdctools_3_30_06_67_core/packages/xdc/xdc.tci
C:/ti/xdctools_3_30_06_67_core/packages/xdc/template.xs:
package.mak: C:/ti/xdctools_3_30_06_67_core/packages/xdc/template.xs
C:/ti/xdctools_3_30_06_67_core/packages/xdc/om2.xs:
package.mak: C:/ti/xdctools_3_30_06_67_core/packages/xdc/om2.xs
C:/ti/xdctools_3_30_06_67_core/packages/xdc/xmlgen.xs:
package.mak: C:/ti/xdctools_3_30_06_67_core/packages/xdc/xmlgen.xs
C:/ti/xdctools_3_30_06_67_core/packages/xdc/xmlgen2.xs:
package.mak: C:/ti/xdctools_3_30_06_67_core/packages/xdc/xmlgen2.xs
C:/ti/xdctools_3_30_06_67_core/packages/xdc/Warnings.xs:
package.mak: C:/ti/xdctools_3_30_06_67_core/packages/xdc/Warnings.xs
C:/ti/xdctools_3_30_06_67_core/packages/xdc/IPackage.xs:
package.mak: C:/ti/xdctools_3_30_06_67_core/packages/xdc/IPackage.xs
C:/ti/xdctools_3_30_06_67_core/packages/xdc/package.xs:
package.mak: C:/ti/xdctools_3_30_06_67_core/packages/xdc/package.xs
C:/ti/xdctools_3_30_06_67_core/packages/xdc/services/global/Clock.xs:
package.mak: C:/ti/xdctools_3_30_06_67_core/packages/xdc/services/global/Clock.xs
C:/ti/xdctools_3_30_06_67_core/packages/xdc/services/global/Trace.xs:
package.mak: C:/ti/xdctools_3_30_06_67_core/packages/xdc/services/global/Trace.xs
C:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/bld.js:
package.mak: C:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/bld.js
C:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/BuildEnvironment.xs:
package.mak: C:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/BuildEnvironment.xs
C:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/PackageContents.xs:
package.mak: C:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/PackageContents.xs
C:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/_gen.xs:
package.mak: C:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/_gen.xs
C:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/Library.xs:
package.mak: C:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/Library.xs
C:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/Executable.xs:
package.mak: C:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/Executable.xs
C:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/Repository.xs:
package.mak: C:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/Repository.xs
C:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/Configuration.xs:
package.mak: C:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/Configuration.xs
C:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/Script.xs:
package.mak: C:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/Script.xs
C:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/Manifest.xs:
package.mak: C:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/Manifest.xs
C:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/Utils.xs:
package.mak: C:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/Utils.xs
C:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/ITarget.xs:
package.mak: C:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/ITarget.xs
C:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/ITarget2.xs:
package.mak: C:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/ITarget2.xs
C:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/ITarget3.xs:
package.mak: C:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/ITarget3.xs
C:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/ITargetFilter.xs:
package.mak: C:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/ITargetFilter.xs
C:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/package.xs:
package.mak: C:/ti/xdctools_3_30_06_67_core/packages/xdc/bld/package.xs
package.mak: config.bld
C:/ti/bios_6_42_02_29/packages/ti/targets/ITarget.xs:
package.mak: C:/ti/bios_6_42_02_29/packages/ti/targets/ITarget.xs
C:/ti/bios_6_42_02_29/packages/ti/targets/C28_large.xs:
package.mak: C:/ti/bios_6_42_02_29/packages/ti/targets/C28_large.xs
C:/ti/bios_6_42_02_29/packages/ti/targets/C28_float.xs:
package.mak: C:/ti/bios_6_42_02_29/packages/ti/targets/C28_float.xs
C:/ti/bios_6_42_02_29/packages/ti/targets/package.xs:
package.mak: C:/ti/bios_6_42_02_29/packages/ti/targets/package.xs
C:/ti/bios_6_42_02_29/packages/ti/targets/arm/elf/IArm.xs:
package.mak: C:/ti/bios_6_42_02_29/packages/ti/targets/arm/elf/IArm.xs
C:/ti/bios_6_42_02_29/packages/ti/targets/arm/elf/package.xs:
package.mak: C:/ti/bios_6_42_02_29/packages/ti/targets/arm/elf/package.xs
package.mak: package.bld
C:/ti/xdctools_3_30_06_67_core/packages/xdc/tools/configuro/template/compiler.opt.xdt:
package.mak: C:/ti/xdctools_3_30_06_67_core/packages/xdc/tools/configuro/template/compiler.opt.xdt
C:/ti/xdctools_3_30_06_67_core/packages/xdc/services/io/File.xs:
package.mak: C:/ti/xdctools_3_30_06_67_core/packages/xdc/services/io/File.xs
C:/ti/xdctools_3_30_06_67_core/packages/xdc/services/io/package.xs:
package.mak: C:/ti/xdctools_3_30_06_67_core/packages/xdc/services/io/package.xs
C:/ti/xdctools_3_30_06_67_core/packages/xdc/tools/configuro/template/compiler.defs.xdt:
package.mak: C:/ti/xdctools_3_30_06_67_core/packages/xdc/tools/configuro/template/compiler.defs.xdt
C:/ti/xdctools_3_30_06_67_core/packages/xdc/tools/configuro/template/custom.mak.exe.xdt:
package.mak: C:/ti/xdctools_3_30_06_67_core/packages/xdc/tools/configuro/template/custom.mak.exe.xdt
C:/ti/xdctools_3_30_06_67_core/packages/xdc/tools/configuro/template/package.xs.xdt:
package.mak: C:/ti/xdctools_3_30_06_67_core/packages/xdc/tools/configuro/template/package.xs.xdt
endif

ti.targets.arm.elf.A8Fnv.rootDir ?= C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.4
ti.targets.arm.elf.packageBase ?= C:/ti/bios_6_42_02_29/packages/ti/targets/arm/elf/
.PRECIOUS: $(XDCCFGDIR)/%.oea8fnv
.PHONY: all,ea8fnv .dlls,ea8fnv .executables,ea8fnv test,ea8fnv
all,ea8fnv: .executables,ea8fnv
.executables,ea8fnv: .libraries,ea8fnv
.executables,ea8fnv: .dlls,ea8fnv
.dlls,ea8fnv: .libraries,ea8fnv
.libraries,ea8fnv: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,ea8fnv
	@$(ECHO) xdc .executables,ea8fnv
	@$(ECHO) xdc .libraries,ea8fnv
	@$(ECHO) xdc .dlls,ea8fnv


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_configPkg.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package configPkg" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

.dlls,ea8fnv .dlls: app.pea8fnv

-include package/cfg/app_pea8fnv.mak
-include package/cfg/app_pea8fnv.cfg.mak
ifeq (,$(MK_NOGENDEPS))
-include package/cfg/app_pea8fnv.dep
endif
app.pea8fnv: package/cfg/app_pea8fnv.xdl
	@


ifeq (,$(wildcard .libraries,ea8fnv))
app.pea8fnv package/cfg/app_pea8fnv.c: .libraries,ea8fnv
endif

package/cfg/app_pea8fnv.c package/cfg/app_pea8fnv.h package/cfg/app_pea8fnv.xdl: override _PROG_NAME := app.xea8fnv
package/cfg/app_pea8fnv.c: package/cfg/app_pea8fnv.cfg
package/cfg/app_pea8fnv.xdc.inc: package/cfg/app_pea8fnv.xdl
package/cfg/app_pea8fnv.xdl package/cfg/app_pea8fnv.c: .interfaces

clean:: clean,ea8fnv
	-$(RM) package/cfg/app_pea8fnv.cfg
	-$(RM) package/cfg/app_pea8fnv.dep
	-$(RM) package/cfg/app_pea8fnv.c
	-$(RM) package/cfg/app_pea8fnv.xdc.inc

clean,ea8fnv::
	-$(RM) app.pea8fnv
.executables,ea8fnv .executables: app.xea8fnv

app.xea8fnv: |app.pea8fnv

-include package/cfg/app.xea8fnv.mak
app.xea8fnv: package/cfg/app_pea8fnv.oea8fnv 
	$(RM) $@
	@$(MSG) lnkea8fnv $@ ...
	$(RM) $(XDCCFGDIR)/$@.map
	$(ti.targets.arm.elf.A8Fnv.rootDir)/bin/armlnk -w -q -u _c_int00 -fs $(XDCCFGDIR)$(dir $@).  -q -o $@ package/cfg/app_pea8fnv.oea8fnv   package/cfg/app_pea8fnv.xdl --silicon_version=7A8 --strict_compatibility=on -c -m $(XDCCFGDIR)/$@.map -l $(ti.targets.arm.elf.A8Fnv.rootDir)/lib/libc.a
	
app.xea8fnv: export C_DIR=
app.xea8fnv: PATH:=$(ti.targets.arm.elf.A8Fnv.rootDir)/bin/;$(PATH)
app.xea8fnv: Path:=$(ti.targets.arm.elf.A8Fnv.rootDir)/bin/;$(PATH)

app.test test,ea8fnv test: app.xea8fnv.test

app.xea8fnv.test:: app.xea8fnv
ifeq (,$(_TESTLEVEL))
	@$(MAKE) -R -r --no-print-directory -f $(XDCROOT)/packages/xdc/bld/xdc.mak _TESTLEVEL=1 app.xea8fnv.test
else
	@$(MSG) running $<  ...
	$(call EXEC.app.xea8fnv, ) 
endif

clean,ea8fnv::
	-$(RM) $(wildcard .tmp,app.xea8fnv,*)


clean:: clean,ea8fnv

clean,ea8fnv::
	-$(RM) app.xea8fnv
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
app_pea8fnv.oea8fnv,copy : package/cfg/app_pea8fnv.oea8fnv
app_pea8fnv.sea8fnv,copy : package/cfg/app_pea8fnv.sea8fnv

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg $(XDCROOT)/packages/xdc/cfg/Main.xs | .interfaces
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,configPkg
ifeq (,$(MK_NOGENDEPS))
-include package/rel/configPkg.tar.dep
endif
package/rel/configPkg/configPkg/package/package.rel.xml: package/package.bld.xml
package/rel/configPkg/configPkg/package/package.rel.xml: package/build.cfg
package/rel/configPkg/configPkg/package/package.rel.xml: package/package.xdc.inc
package/rel/configPkg/configPkg/package/package.rel.xml: .force
	@$(MSG) generating external release references $@ ...
	$(XS) $(JSENV) -f $(XDCROOT)/packages/xdc/bld/rel.js $(MK_RELOPTS) . $@

configPkg.tar: package/rel/configPkg.xdc.inc package/rel/configPkg/configPkg/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/configPkg.xdc.inc,package/rel/configPkg.tar.dep)


release release,configPkg: all configPkg.tar
clean:: .clean
	-$(RM) configPkg.tar
	-$(RM) package/rel/configPkg.xdc.inc
	-$(RM) package/rel/configPkg.tar.dep

clean:: .clean
	-$(RM) .libraries $(wildcard .libraries,*)
clean:: 
	-$(RM) .dlls $(wildcard .dlls,*)
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
endif
clean::
	-$(RMDIR) package

include custom.mak
